name: glances_monitor
description: "Flutter приложение для мониторинга серверов через Glances REST API"
publish_to: 'none'

version: 0.0.1+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
